import React, { useEffect, useRef, useState } from 'react'
import { AlertCircle, AlertTriangle, CheckCircle2, Info, X } from 'lucide-react'
export function fmtTime(sec?: number): string { if (!sec || sec <= 0) return '—'; const d = new Date(sec * 1000); const diff = d.getTime() - Date.now(), abs = Math.abs(diff); const rel = abs < 60000 ? (diff > 0 ? '即将' : '刚刚') : abs < 3600000 ? (diff > 0 ? `${Math.round(abs / 60000)} 分钟后` : `${Math.round(abs / 60000)} 分钟前`) : abs < 86400000 ? (diff > 0 ? `${Math.round(abs / 3600000)} 小时后` : `${Math.round(abs / 3600000)} 小时前`) : diff > 0 ? `${Math.round(abs / 86400000)} 天后` : `${Math.round(abs / 86400000)} 天前`; return `${d.toLocaleString('zh-CN', { hour12: false })}（${rel}）` }
export function fmtISO(iso?: string): string { if (!iso) return '—'; const t = Date.parse(iso); if (!t || t <= 0 || new Date(t).getFullYear() < 1980) return '—'; const d = new Date(t), diff = Date.now() - t; if (diff < 0) return d.toLocaleString('zh-CN', { hour12: false }); if (diff < 60000) return '刚刚'; if (diff < 3600000) return `${Math.round(diff / 60000)} 分钟前`; if (diff < 86400000) return `${Math.round(diff / 3600000)} 小时前`; if (diff < 2592000000) return `${Math.round(diff / 86400000)} 天前`; return d.toLocaleString('zh-CN', { hour12: false }) }
export function fmtDuration(sec?: number): string { if (sec === undefined || sec === null || sec <= 0) return '—'; const h = Math.floor(sec / 3600), m = Math.floor((sec % 3600) / 60), s = Math.floor(sec % 60); if (h > 0) return `${h}小时${m}分`; if (m > 0) return `${m}分${s}秒`; return `${s}秒` }
export function fmtNum(n?: number): string { return n === undefined || n === null ? '—' : n.toLocaleString('en-US') }
export function shortUID(uid: string): string { return uid.length > 8 ? uid.slice(0, 8) : uid }
export function displayName(a: { nickname?: string; uid: string }): string { return a.nickname || shortUID(a.uid) }
export function statusBadge(status: string): { cls: string; text: string } { switch (status) { case 'healthy': return { cls: 'badge-ok', text: '正常' }; case 'cooling': return { cls: 'badge-warn', text: '冷却中' }; case 'disabled': return { cls: 'badge-danger', text: '已禁用' }; case 'token_expired': return { cls: 'badge-danger', text: 'Token 过期' }; case 'gateway_unreachable': return { cls: 'badge-dim', text: '网关不可达' }; case 'missing_credential': return { cls: 'badge-warn', text: '凭证缺失' }; default: return { cls: 'badge-dim', text: '未加载' } } }
export function coolKindText(kind?: string): string { return kind === 'hard_credit' ? '余额不足' : kind === 'soft_rate' ? '被限流' : '冷却' }
export function Badge({ cls, children }: { cls: string; children: React.ReactNode }) { return <span className={`badge ${cls}`}><span className="badge-dot" />{children}</span> }
export function Alert({ kind, children, onClose }: { kind: 'error' | 'warn' | 'ok' | 'info'; children: React.ReactNode; onClose?: () => void }) { const Icon = { error: AlertCircle, warn: AlertTriangle, ok: CheckCircle2, info: Info }[kind]; return <div className={`alert alert-${kind} apple-alert`} role={kind === 'error' ? 'alert' : 'status'}><span className="alert-icon"><Icon size={17} strokeWidth={1.9} aria-hidden="true" /></span><div className="apple-alert-copy">{children}</div>{onClose && <button className="btn btn-ghost btn-sm btn-icon" onClick={onClose} aria-label="关闭"><X size={14} /></button>}</div> }
export function Modal({ title, onClose, children, wide, className, footer }: { title: string; onClose: () => void; children: React.ReactNode; wide?: boolean; className?: string; footer?: React.ReactNode }) {
  const [dragY, setDragY] = useState(0)
  const ref = useRef<{ id: number; startY: number; lastY: number; lastT: number; velocity: number } | null>(null)
  useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose() }; document.addEventListener('keydown', onKey); const prev = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.removeEventListener('keydown', onKey); document.body.style.overflow = prev } }, [onClose])
  const down = (e: React.PointerEvent) => { ref.current = { id: e.pointerId, startY: e.clientY, lastY: e.clientY, lastT: performance.now(), velocity: 0 }; (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId) }
  const move = (e: React.PointerEvent) => { const d = ref.current; if (!d || d.id !== e.pointerId) return; const now = performance.now(), dy = Math.max(0, e.clientY - d.startY), dt = Math.max(1, now - d.lastT); d.velocity = (e.clientY - d.lastY) / dt; d.lastY = e.clientY; d.lastT = now; setDragY(dy < 180 ? dy : 180 + (dy - 180) * .25) }
  const up = () => { const d = ref.current; if (!d) return; const projected = dragY + d.velocity * 260; ref.current = null; if (projected > 120) { setDragY(0); onClose() } else setDragY(0) }
  return <div className="modal-backdrop apple-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose() }}><div className={`modal apple-sheet ${wide ? 'modal-wide' : ''} ${className || ''}`} role="dialog" aria-modal="true" style={{ transform: dragY ? `translateY(${dragY}px) scale(${1 - Math.min(.04, dragY / 4000)})` : undefined }}><button className="apple-sheet-grabber" aria-label="拖动关闭" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} /><div className="modal-head"><h2>{title}</h2><button className="btn btn-ghost btn-sm btn-icon" onClick={onClose} aria-label="关闭"><X size={15} /></button></div>{children}{footer && <div className="modal-foot">{footer}</div>}</div></div>
}
export function Spinner({ label }: { label?: string }) { return <span className="apple-spinner-wrap"><span className="spinner" />{label && <span className="text-dim">{label}</span>}</span> }
export function Empty({ children }: { children: React.ReactNode }) { return <div className="empty apple-empty">{children}</div> }
export function ConfirmDialog({ title, message, confirmText = '确认', danger, onConfirm, onCancel, busy }: { title: string; message: React.ReactNode; confirmText?: string; danger?: boolean; onConfirm: () => void; onCancel: () => void; busy?: boolean }) { return <Modal title={title} onClose={onCancel} footer={<><button className="btn" onClick={onCancel} disabled={busy}>取消</button><button className={`btn ${danger ? 'btn-danger' : 'btn-primary'}`} onClick={onConfirm} disabled={busy}>{busy ? <Spinner /> : null}{confirmText}</button></>}><div className="apple-confirm-copy">{message}</div></Modal> }